update_notification: true # if true, the plugin will notify you when a new version is available
time_limits: # time limits in seconds
  default: 3600
  vip: 7200
  op: 0
world_whitelist_system:
  enabled: false  # if enabled, time limits will be divided by worlds
  worlds:
  - world
  - world_nether
  - world_the_end
  teleport_coordinates_on_kick: spawn;0;60;0;90;0
reset_time: "05:00" # defaults to 00:00 EST, change to your timezone
information_message_enabled_by_default: true
data_save_time: 3
action_bar: false
boss_bar:
  enabled: true
  color: BLUE # RED, PINK, PURPLE, BLUE, LIGHT_BLUE, CYAN, GREEN, YELLOW, ORANGE, WHITE, GRAY, BLACK
  style: SEGMENTED_10
notification:
  60:
    message:
    - ""
    - "{centered}&c&lWARNING!"
    - "{centered}&cYou have &71 hour &cleft to play on the server."
    - ""
  30:
    message:
    - ""
    - "{centered}&c&lWARNING!"
    - "{centered}&cYou have &730 minutes &cleft to play on the server."
    - ""
  15:
    message:
    - ""
    - "{centered}&c&lWARNING!"
    - "{centered}&cYou have &715 minutes &cleft to play on the server."
    - ""
  5:
    message:
    - ""
    - "{centered}&c&lWARNING!"
    - "{centered}&cYou have &75 minutes &cleft to play on the server."
    - ""
  1:
    message:
    - ""
    - "{centered}&c&lWARNING!"
    - "{centered}&cYou have &71 minute &cleft to play on the server."
    - ""
