main: blarnix.PlayerTimeLimit
version: DEV-1.7
name: PlayerTimeLimit
api-version: 1.13
author: Blarnix
softdepend: [Multiverse-Core,PlaceholderAPI]
commands:
  playertimelimit:
    description: Main command of PlayerTimeLimit
    aliases: [ptl]
    aliases: [ptl]
